.tests:
  script:
    - bundle exec rake

.benchmark:
  script:
    - bundle exec rake benchmarks

default:
  before_script:
    - gem install bundler --no-document
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"

ruby_2_2:
  image: ruby:2.2
  extends:
    - .tests
  before_script:
    - gem install bundler -v 1.17.3 --no-document
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"

ruby_2_3:
  image: ruby:2.3
  extends:
    - .tests
    - .benchmark

ruby_2_4:
  image: ruby:2.4
  extends:
    - .tests
    - .benchmark

ruby_2_5:
  image: ruby:2.5
  extends:
    - .tests
    - .benchmark
