# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cccc77621d51855a12885097c1cbda929c708945fb070b6e08437f68e31c8a2b2d6ea9d23729484d6d77a67978bef44b7d50ac0a9d8baee4ad4935d9b7c8c29e

test:
  secret_key_base: 705c70ed1c5324ccf84a364f9cbc60a21f72b7c17a2c5c5b97e0ec0fd28652dc78e5fd2da370ed9a8757b15298d124ff6361d457366cf4cd0e797f68f9f150cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
